type PermissionLabelMap = Record<string, string>;

export const PERMISSION_LABELS: PermissionLabelMap = {
  ITEM_READ: "Visualizar itens",
  ITEM_CREATE: "Criar itens",
  ITEM_UPDATE: "Atualizar itens",
  ITEM_DELETE: "Excluir itens",
  USER_READ: "Visualizar utilizadores",
  USER_CREATE: "Criar utilizadores",
  USER_UPDATE: "Atualizar utilizadores",
  USER_DELETE: "Excluir utilizadores",
  CARGO_READ: "Visualizar cargos",
  CARGO_CREATE: "Criar cargos",
  CARGO_UPDATE: "Atualizar cargos",
  CARGO_DELETE: "Excluir cargos",
  CATEGORIA_READ: "Visualizar categorias",
  CATEGORIA_CREATE: "Criar categorias",
  CATEGORIA_UPDATE: "Atualizar categorias",
  CATEGORIA_DELETE: "Excluir categorias",
  SALA_READ: "Visualizar salas",
  SALA_CREATE: "Criar salas",
  SALA_UPDATE: "Atualizar salas",
  SALA_DELETE: "Excluir salas",
  DEPARTAMENTO_READ: "Visualizar departamentos",
  DEPARTAMENTO_CREATE: "Criar departamentos",
  DEPARTAMENTO_UPDATE: "Atualizar departamentos",
  DEPARTAMENTO_DELETE: "Excluir departamentos",
  INSTITUICAO_READ: "Visualizar instituição",
  INSTITUICAO_CREATE: "Criar instituição",
  INSTITUICAO_UPDATE: "Atualizar instituição",
  INSTITUICAO_DELETE: "Excluir instituição",
  CONDICAO_READ: "Visualizar condições",
  CONDICAO_CREATE: "Criar condições",
  CONDICAO_UPDATE: "Atualizar condições",
  CONDICAO_DELETE: "Excluir condições",
  REGISTO_READ: "Visualizar registos",
  REGISTO_CREATE: "Criar registos",
  REGISTO_UPDATE: "Atualizar registos",
  REGISTO_DELETE: "Excluir registos",
};
