export const PERMISSIONS = {
  CREATE_ITEM: "CREATE_ITEM",
  READ_ITEM: "READ_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_CARGOS: "MANAGE_CARGOS",
  MANAGE_CATEGORIAS: "MANAGE_CATEGORIAS",
  MANAGE_SALAS: "MANAGE_SALAS",
} as const;
